services:
  app:
    build:
      context: .
      dockerfile: /Dockerfile  # Specify the relative path to your Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge