services:
  app:
    build:
      context: .
      dockerfile: /Dockerfile # Specify the relative path to your Dockerfile
    ports:
      - "${VITE_PORT}:5180"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
