services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile # Specify the relative path to your Dockerfile
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    networks:
      - app-network
    environment:
      - VITE_APP_SITEKEY=${VITE_APP_SITEKEY}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_MAX_IDLE_TIME=${VITE_MAX_IDLE_TIME}
      - VITE_S3_URL=${VITE_S3_URL}
      - VITE_S3_DELETE_URL=${VITE_S3_DELETE_URL}

networks:
  app-network:
    driver: bridge
