export const demoSidePanel = [
  {
    id: 1,
    name: "Dashboard",
    code: "dashboard",
    show_menu: true,
    parent: null,
    is_parent: true,
    is_root: true,
    index: 10,
    link: "/admin/dashboard",
    icon: "fa fa-chart-line",
    access_type: "full_access",
    children: [],
  },
  {
    id: 4,
    name: "Staff",
    code: "staff",
    show_menu: true,
    parent: null,
    is_parent: true,
    is_root: true,
    index: 20,
    link: "/admin/staff",
    icon: "fa fa-user",
    access_type: "full_access",
    children: [],
  },
  {
    id: 10,
    name: "System Setting",
    code: "sys_set",
    show_menu: true,
    parent: null,
    is_parent: true,
    is_root: true,
    index: 30,
    link: "/",
    icon: "fa fa-gear",
    access_type: null,
    children: [
      {
        id: 5,
        name: "Role & Access Management",
        code: "role",
        parent: "sys_set",
        show_menu: false,
        is_parent: false,
        is_root: false,
        index: 31,
        link: "/admin/roles",
        icon: "fa fa-user-lock",
        access_type: "full_access",
        children: [],
      },
    ],
  },
];
